### ISSUE TITLE
Use LATEST_RELEASE file rather than guessing

### ISSUE THREAD

**Issue by swrobel** [flavorjones/chromedriver-helper#62]
There's currently something weird going on where there's a folder on the [Chromedriver google storage folder](https://chromedriver.storage.googleapis.com/index.html) that seems out of sync with the rest of the Chromedriver versions (70.0.3538.16 vs 2.42 which should be latest). This tool picks up 70.0.3538.16 as the latest version, rather than 2.42 as specified in the [LATEST_RELEASE](https://chromedriver.storage.googleapis.com/LATEST_RELEASE) file.

<img width="729" alt="https___chromedriver_storage_googleapis_com_index_html" src="https://user-images.githubusercontent.com/157270/45653256-60ba6a80-baa5-11e8-9dc0-34023cd6097f.png">

**Comment by ibrahima** [comment]
Also, it looks like this version of ChromeDriver has a different directory structure in the zip file - it puts the executable in a directory named `chromedriver_linux64` instead of `linux64`, and chromedriver-helper then crashes when trying to update because it doesn't expect the binary to be in that directory.

**Comment by CalebRouleau** [comment]
Hi all,

ChromeDriver is working on a potential change to its version model that uses the Chrome version system instead of our custom system 70.0.3538.16 is a Chrome-style version number and it corresponds to the version number you can find by going to chrome://version/. I think using LATEST_RELEASE is a good solution for you for now.

**Comment by JohnChen0** [comment]
This is an experiment of future release model of ChromeDriver. As such it may still have issues that need to be resolved. I'd recommend tools to use LATEST_RELEASE to pick up the ChromeDriver to use, instead of scanning the directory.

**Comment by swrobel** [comment]
FYI, response from chromedriver team recommends making this change: https://groups.google.com/d/msg/chromedriver-users/NVC4tnXS58k/LNw6rBlBCAAJ

**Comment by flavorjones** [comment]
Working on this now.

**Comment by flavorjones** [comment]
I've merged @ibrahima's pull request #63 and will cut v2.0.2 to address this shortly.

**Comment by flavorjones** [comment]
Correction, the new release will be v2.1.0.

**Comment by flavorjones** [comment]
v2.1.0 has been released. Thanks all for your patience, and thanks @ibrahima for the PR!

![ooo-high-five](https://user-images.githubusercontent.com/8207/45723468-6e442300-bb7f-11e8-9e5a-2ec59fc9c9eb.gif)
